version: '3'
services:
  ghost_blog:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      - database__client=mysql
      - database__connection__database=ghost
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=root
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
       MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10